[tool.poetry]
name = "curs4"
version = "0.1.0"
description = ""
authors = ["vitali <sh015@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
